import { useCallback, useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { Button, Card, EmptyState, PageHeader, Pagination, SearchBox, Select, Skeleton, StatCard, StatusChip } from "../../../design-system";
import { listSocieties, getSociety } from "../../../services/societyApi";
import { listStudents, getStudent } from "../../students/services/studentMasterApi";
import { claimCounts, joinCounts } from "../../approvals/services/approvalApi";
import { listAssignedEventReviews } from "../../events/services/eventApi";
import { getWorkspaceEvent, listAllEvents } from "../services/workspaceApi";

const fmt = (value) => value ? new Date(value).toLocaleDateString() : "—";
const lifecycle = (event) => { const now = new Date(); return event.startDate && new Date(event.startDate) > now ? "UPCOMING" : event.endDate && new Date(event.endDate) < now ? "PAST" : "ONGOING"; };
export function WorkspaceDashboardPage({ title }) {
  const [state, setState] = useState({ loading: true, metrics: {}, recent: [], error: "" });
  useEffect(() => { Promise.allSettled([claimCounts(), joinCounts(), listAssignedEventReviews({ status: "PENDING" }), listSocieties({ isActive: true, limit: 1 }), listAllEvents({ from: new Date().toISOString().slice(0, 10), limit: 5 })]).then(([claims, joins, reviews, societies, events]) => { const value = (result, fallback) => result.status === "fulfilled" ? result.value : fallback, claim = value(claims, {}), join = value(joins, {}), review = value(reviews, {}), society = value(societies, {}), event = value(events, {}); setState({ loading: false, error: "", metrics: { pending: (claim.PENDING || 0) + (join.PENDING || 0), eventActions: review.pagination?.totalItems ?? review.items?.length, societies: society.pagination?.totalItems, upcoming: event.pagination?.totalItems }, recent: review.items?.slice(0, 5) || [] }); }); }, []);
  if (state.loading) return <Skeleton lines={8}/>;
  return <div className="page-stack"><PageHeader title={`${title} Dashboard`} description="Live operational information from the shared portal records."/><div className="workspace-metrics"><Metric label="Pending Approvals" value={state.metrics.pending}/><Metric label="Events Awaiting Action" value={state.metrics.eventActions}/><Metric label="Active Societies" value={state.metrics.societies}/><Metric label="Upcoming Events" value={state.metrics.upcoming}/></div><Card title="Needs Attention">{state.recent.length ? state.recent.map((review) => <p key={review._id}><b>{review.eventId?.eventCode}</b> {review.eventId?.title || "Event review"} · <StatusChip status={review.status}/></p>) : <EmptyState title="No assigned items need attention"/>}</Card></div>;
}
function Metric({ label, value }) { return value == null ? <Card title={label}><span className="muted">Unavailable</span></Card> : <StatCard label={label} value={value}/>; }
export function EventBrowserPage({ basePath = "/admin/events", title = "Events" }) {
  const [filters, setFilters] = useState({ search: "", societyId: "", status: "", approvalStatus: "", from: "", to: "", page: 1, limit: 20 }), [state, setState] = useState({ loading: true, items: [], pagination: {}, error: "" }), [societies, setSocieties] = useState([]);
  const load = useCallback(() => { setState((old) => ({ ...old, loading: true, error: "" })); const params = Object.fromEntries(Object.entries(filters).filter(([, value]) => value !== "")); listAllEvents(params).then((result) => setState({ loading: false, items: result.items || [], pagination: result.pagination || {}, error: "" })).catch((error) => setState({ loading: false, items: [], pagination: {}, error: error.readableMessage })); }, [filters]);
  useEffect(() => { load(); }, [load]); useEffect(() => { listSocieties({ limit: 100 }).then((result) => setSocieties(result.items || [])).catch(() => {}); }, []);
  const set = (key, value) => setFilters((old) => ({ ...old, [key]: value, page: key === "page" ? value : 1 }));
  return <div className="page-stack"><PageHeader title={title} description="System-wide events from the authoritative Event module."/><div className="workspace-filters"><SearchBox value={filters.search} onChange={(e) => set("search", e.target.value)} placeholder="Search event name or code"/><Select label="Society" value={filters.societyId} onChange={(e) => set("societyId", e.target.value)} options={[{ value: "", label: "All Societies" }, ...societies.map((society) => ({ value: society._id, label: `${society.name} (${society.code})` }))]}/><Select label="Status" value={filters.status} onChange={(e) => set("status", e.target.value)} options={[{ value: "", label: "All statuses" }, ...["DRAFT","FACULTY_REVIEW","ASSISTANT_REVIEW","DOSA_STAFF_REVIEW","ADOSA_REVIEW","ADMIN_REVIEW","APPROVED","REJECTED","CHANGES_REQUESTED"]]}/><input className="ds-control" aria-label="From date" type="date" value={filters.from} onChange={(e) => set("from", e.target.value)}/><input className="ds-control" aria-label="To date" type="date" value={filters.to} onChange={(e) => set("to", e.target.value)}/></div>{state.loading ? <Skeleton lines={8}/> : state.error ? <EmptyState title="Events unavailable" description={state.error} action={<Button onClick={load}>Retry</Button>}/> : !state.items.length ? <EmptyState title="No events found"/> : <div className="workspace-table"><table><thead><tr><th>Event</th><th>Society</th><th>Date</th><th>Venue</th><th>Lifecycle</th><th>Status</th></tr></thead><tbody>{state.items.map((event) => <tr key={event._id}><td><Link to={`${basePath}/${event._id}`}><b>{event.eventCode}</b><small>{event.title || "Untitled Event"}</small></Link></td><td>{event.societyId?.name || "—"}</td><td>{fmt(event.startDate)} – {fmt(event.endDate)}</td><td>{event.venueRequirement?.preferredVenueName || "—"}</td><td><StatusChip status={lifecycle(event)}/></td><td><StatusChip status={event.approvalStatus || event.status}/></td></tr>)}</tbody></table></div>}<Pagination page={filters.page} totalPages={Math.max(1, state.pagination.totalPages || 1)} onChange={(page) => set("page", page)}/></div>;
}
export function EventDetailsPage() { const { eventId } = useParams(), [state, setState] = useState({ loading: true, item: null, error: "" }); useEffect(() => { getWorkspaceEvent(eventId).then((item) => setState({ loading: false, item, error: "" })).catch((error) => setState({ loading: false, item: null, error: error.readableMessage })); }, [eventId]); if (state.loading) return <Skeleton lines={10}/>; if (state.error) return <EmptyState title="Event unavailable" description={state.error}/>; const event = state.item; return <div className="page-stack"><PageHeader title={event.title || "Untitled Event"} description={`${event.eventCode} · ${event.societyId?.name || "Society"}`}/><Card title="Event Details"><dl className="workspace-details"><dt>Date</dt><dd>{fmt(event.startDate)} – {fmt(event.endDate)}</dd><dt>Venue</dt><dd>{event.venueRequirement?.preferredVenueName || "—"}</dd><dt>Status</dt><dd><StatusChip status={event.status}/></dd><dt>Objective</dt><dd>{event.objective || "—"}</dd></dl></Card><Card title="Approval History">{event.reviewHistory?.length ? event.reviewHistory.map((review) => <p key={review._id}>{review.stage?.replaceAll("_", " ")} · {review.status} · {fmt(review.decidedAt || review.assignedAt)}</p>) : <p className="muted">No approval history recorded.</p>}</Card></div>; }
export function SocietyBrowserPage({ basePath }) { const [search, setSearch] = useState(""), [state, setState] = useState({ loading: true, items: [], error: "" }); useEffect(() => { listSocieties({ search, limit: 100 }).then((result) => setState({ loading: false, items: result.items || [], error: "" })).catch((error) => setState({ loading: false, items: [], error: error.readableMessage })); }, [search]); return <div className="page-stack"><PageHeader title="Societies" description="Read-only Society Master visibility."/><SearchBox value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search society name or code"/>{state.loading ? <Skeleton lines={8}/> : state.error ? <EmptyState title="Societies unavailable" description={state.error}/> : <div className="workspace-table"><table><thead><tr><th>Code</th><th>Society</th><th>Category</th><th>Status</th></tr></thead><tbody>{state.items.map((society) => <tr key={society._id}><td><Link to={`${basePath}/${society._id}`}>{society.code}</Link></td><td>{society.name}</td><td>{society.category || "—"}</td><td><StatusChip status={society.status || (society.isActive ? "ACTIVE" : "INACTIVE")}/></td></tr>)}</tbody></table></div>}</div>; }
export function SocietyReadPage() { const { societyId } = useParams(), [item, setItem] = useState(); useEffect(() => { getSociety(societyId).then(setItem); }, [societyId]); return !item ? <Skeleton lines={7}/> : <div className="page-stack"><PageHeader title={item.name} description={item.code}/><Card><dl className="workspace-details"><dt>Category</dt><dd>{item.category || "—"}</dd><dt>Status</dt><dd><StatusChip status={item.status || (item.isActive ? "ACTIVE" : "INACTIVE")}/></dd><dt>Description</dt><dd>{item.description || "—"}</dd></dl></Card></div>; }
export function StudentBrowserPage({ basePath }) { const [search, setSearch] = useState(""), [state, setState] = useState({ loading: true, items: [], error: "" }); useEffect(() => { listStudents({ search, limit: 100 }).then((result) => setState({ loading: false, items: result.items || [], error: "" })).catch((error) => setState({ loading: false, items: [], error: error.readableMessage })); }, [search]); return <div className="page-stack"><PageHeader title="Students" description="Read-only Student Master visibility."/><SearchBox value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search name, roll number or student ID"/>{state.loading ? <Skeleton lines={8}/> : state.error ? <EmptyState title="Students unavailable" description={state.error}/> : <div className="workspace-table"><table><thead><tr><th>Student ID</th><th>Name</th><th>Roll Number</th><th>Course</th><th>Status</th></tr></thead><tbody>{state.items.map((student) => <tr key={student._id}><td><Link to={`${basePath}/${student._id}`}>{student.publicId || student.studentId || "—"}</Link></td><td>{student.name}</td><td>{student.rollNumber}</td><td>{[student.course, student.branch].filter(Boolean).join(" · ") || "—"}</td><td><StatusChip status={student.status || student.recordStatus}/></td></tr>)}</tbody></table></div>}</div>; }
export function StudentReadPage() { const { studentId } = useParams(), [item, setItem] = useState(); useEffect(() => { getStudent(studentId).then(setItem); }, [studentId]); return !item ? <Skeleton lines={7}/> : <div className="page-stack"><PageHeader title={item.name} description={item.publicId || item.studentId || item.rollNumber}/><Card><dl className="workspace-details"><dt>Roll Number</dt><dd>{item.rollNumber}</dd><dt>Course</dt><dd>{[item.course, item.branch, item.year].filter(Boolean).join(" · ") || "—"}</dd><dt>Email</dt><dd>{item.email || "—"}</dd><dt>Status</dt><dd><StatusChip status={item.status || item.recordStatus}/></dd></dl></Card></div>; }
export function WorkspaceUnavailablePage({ title, description }) { return <div className="page-stack"><PageHeader title={title}/><EmptyState title={`${title} unavailable`} description={description}/></div>; }
