import {useState} from 'react'
import {ArrowLeft,Edit3,LockKeyhole} from 'lucide-react'
import {useNavigate,useParams} from 'react-router-dom'
import {Button,Card,EmptyState,PageHeader,Skeleton} from '../../../design-system'
import {useToast} from '../../../components/common/toastContext'
import {useStudentDetails} from '../hooks/useStudentDetails'
import {display,formatDate} from '../utils/studentFormatters'
import StudentIdentityPanel from '../components/StudentIdentityPanel'
import StudentSocietyReferences from '../components/StudentSocietyReferences'
import EditStudentModal from '../components/EditStudentModal'
import LoginAccessDialog from '../components/LoginAccessDialog'
import StudentStatusDialog from '../components/StudentStatusDialog'
const Section=({title,values})=><Card title={title}><dl className="student-detail-grid">{values.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{display(value)}</dd></div>)}</dl></Card>
export default function StudentDetailsPage(){const{studentId}=useParams(),navigate=useNavigate(),{notify}=useToast(),details=useStudentDetails(studentId),[editing,setEditing]=useState(false),[login,setLogin]=useState(false),[status,setStatus]=useState(false);if(details.loading)return <Skeleton lines={9}/>;if(details.error||!details.student)return <EmptyState title="Unable to load student" description={details.error} action={<Button onClick={details.reload}>Retry</Button>}/>;const s=details.student,u=details.user;return <div className="page-stack student-details"><PageHeader title={s.name} description="Student master record and portal access details." actions={<div className="student-action-row"><Button variant="ghost" icon={ArrowLeft} onClick={()=>navigate('/admin/students')}>Back</Button><Button icon={Edit3} onClick={()=>setEditing(true)}>Edit</Button><Button variant="outline" icon={LockKeyhole} onClick={()=>setLogin(true)}>{s.isLoginAllowed?'Disable':'Enable'} Login</Button><Button variant="ghost" onClick={()=>setStatus(true)}>Change Status</Button></div>}/><StudentIdentityPanel student={s} user={u}/><div className="student-detail-sections"><Section title="Academic" values={[["Course",s.course],["Branch",s.branch],["Year",s.year],["CGPA",s.cgpa]]}/><Section title="Hostel" values={[["Hostel",s.hostel],["Room Type",s.roomType],["Room Number",s.roomNumber]]}/><Section title="Family and Contact" values={[["Father",s.fatherName],["Father Email",s.fatherEmail],["Father Contact",s.fatherContact],["Mother",s.motherName],["Mother Email",s.motherEmail],["Mother Contact",s.motherContact],["Permanent Address",s.permanentAddress?[s.permanentAddress.line1,s.permanentAddress.line2,s.permanentAddress.city,s.permanentAddress.state,s.permanentAddress.postalCode,s.permanentAddress.country].filter(Boolean).join(', '):null]]}/><Section title="Portal Access" values={[["Login Allowed",s.isLoginAllowed?'Yes':'No'],["Signup Status",s.signupStatus],["Profile Status",s.profileStatus],["Record Status",s.recordStatus]]}/><Section title="Linked User" values={[["Account Type",u?.accountType],["User Status",u?.status],["Login Allowed",u?u.isLoginAllowed?'Yes':'No':null],["Last Login",formatDate(u?.lastLoginAt)],["Onboarding Status",s.signupStatus]]}/></div><StudentSocietyReferences references={s.importedSocietyReferences}/><EditStudentModal open={editing} student={s} onClose={()=>setEditing(false)} onSaved={details.reload} notify={notify}/><LoginAccessDialog student={login?s:null} onClose={()=>setLogin(false)} onSaved={details.reload} notify={notify}/><StudentStatusDialog student={status?s:null} onClose={()=>setStatus(false)} onSaved={details.reload} notify={notify}/></div>}
