/* oxlint-disable no-unused-vars */
import { useCallback, useEffect, useState } from 'react'
import { ArrowLeft, Mail, UserRound } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import EmptyState from '../../../components/common/EmptyState'
import LoadingState from '../../../components/common/LoadingState'
import PageHeader from '../../../components/common/PageHeader'
import StatusBadge from '../../../components/common/StatusBadge'
import { getSociety } from '../../../services/societyApi'
import { getActiveLeadership } from '../../../services/societyLeadershipApi'
import { displayValue, formatDate } from '../../../utils/formatters'
export default function SocietyDetailsPage(){const{societyId}=useParams();const[data,setData]=useState(null);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const load=useCallback(async()=>{setLoading(true);setError('');try{const[society,leadership]=await Promise.all([getSociety(societyId),getActiveLeadership(societyId)]);setData({society,leadership})}catch(e){setError(e.readableMessage)}finally{setLoading(false)}},[societyId]);useEffect(()=>{load()},[load]);if(loading)return <LoadingState/>;if(error)return <EmptyState title="Society unavailable" message={error} actionLabel="Retry" onAction={load}/>;const{s:unused}=data;const s=data.society;return <div className="page-stack"><Link className="button button-ghost" style={{width:'fit-content'}} to="/admin/societies"><ArrowLeft size={18}/>Back to societies</Link><PageHeader title={s.name} subtitle={`${s.code} · ${s.category}`}><StatusBadge status={s.status}/></PageHeader><section className="details-grid"><Detail label="Official email" value={s.email}/><Detail label="Academic session" value={s.academicSession}/><Detail label="Short name" value={s.shortName}/><Detail label="Created" value={formatDate(s.createdAt)}/><Detail label="Updated" value={formatDate(s.updatedAt)}/><Detail label="Activity" value={s.isActive?'Active':'Inactive'}/><div className="detail-item" style={{gridColumn:'1/-1'}}><span>Description</span>{displayValue(s.description)}</div></section><section><div className="section-title"><h3>Active leadership</h3></div>{data.leadership.length?<div className="society-list">{data.leadership.map(l=><article className="card" key={l._id}><div className="society-top"><div><h3 style={{margin:0}}>{l.name}</h3><span className="badge badge-active">{l.role.replace('_',' ')}</span></div><UserRound/></div><p><Mail size={15}/> {l.email}</p><div className="society-meta"><div>Designation<strong>{displayValue(l.designation)}</strong></div><div>Department<strong>{displayValue(l.department)}</strong></div><div>Session<strong>{l.academicSession}</strong></div></div></article>)}</div>:<EmptyState title="No active leadership" message="Active Presidents and Vice Presidents will appear here."/>}</section></div>}
function Detail({label,value}){return <div className="detail-item"><span>{label}</span>{displayValue(value)}</div>}
