import { useRef, useState } from "react";
import { confirmMasterImport, downloadMasterTemplate, previewMasterImport } from "../services/settingsApi";

export default function MasterImportControls({ type, label, onImported }) {
  const inputRef = useRef(null);
  const [file, setFile] = useState(null), [preview, setPreview] = useState(null), [message, setMessage] = useState(""), [busy, setBusy] = useState(false);
  const reset = () => { setFile(null); setPreview(null); setMessage(""); if (inputRef.current) inputRef.current.value = ""; };
  const selectFile = async (event) => { const selected = event.target.files?.[0]; if (!selected) return; setFile(selected); setPreview(null); setMessage(""); setBusy(true); try { setPreview(await previewMasterImport(type, selected)); } catch (error) { setMessage(error.readableMessage); } finally { setBusy(false); } };
  const confirm = async () => { setBusy(true); try { const result = await confirmMasterImport(type, preview.importSessionId); reset(); await onImported(); setMessage(`${label} import completed: ${result.inserted} inserted, ${result.skipped} skipped.`); } catch (error) { setMessage(error.readableMessage); } finally { setBusy(false); } };
  const invalid = preview ? (preview.summary.invalid ?? preview.summary.rejected ?? 0) : 0;
  return <div className="master-import"><div className="master-import-actions"><button className="master-import-secondary" type="button" onClick={() => downloadMasterTemplate(type)}>Download Template</button><button className="master-import-primary" type="button" disabled={busy} onClick={() => inputRef.current?.click()}>{busy ? "Processing…" : "Upload Excel"}</button><input ref={inputRef} className="master-file-input" type="file" accept=".xlsx" onChange={selectFile}/></div>{message && <p className="master-import-message">{message}</p>}{file && <div className="master-import-preview"><div className="master-import-summary"><strong>{file.name}</strong>{preview ? <span>{preview.summary.total} total · {preview.summary.valid} valid · {invalid} invalid/skipped</span> : <span>Preparing preview…</span>}</div>{preview && <><div className="master-table-wrap"><table><thead><tr><th>Row</th><th>Code</th><th>Name</th><th>Validation</th></tr></thead><tbody>{preview.rows.map((row) => <tr key={row.rowNumber}><td>{row.rowNumber}</td><td>{row.code}</td><td>{row.name}</td><td>{row.importable ? "Valid" : row.errors.join(", ")}</td></tr>)}</tbody></table></div><div className="master-actions"><button className="master-import-primary" type="button" disabled={busy || !preview.summary.valid} onClick={confirm}>Confirm Import</button><button className="master-import-secondary" type="button" disabled={busy} onClick={reset}>Cancel / Reset</button></div></>}</div>}</div>;
}
