import { useEffect, useRef, useState } from "react";
import * as api from "../services/settingsApi";

const labels={totalStudents:"Total Students",suggestedUpdates:"Suggested Updates",noChange:"No Change",reviewRequired:"Review Required",inactiveSkipped:"Inactive / Skipped",alreadyRolledOver:"Already Rolled Over",invalid:"Invalid"};
export default function StudentRolloverPanel({ sessions, onCompleted, notify }) {
  const current=sessions.find((item)=>item.isCurrent),source=[...sessions].filter((item)=>current&&new Date(item.startDate)<new Date(current.startDate)).sort((a,b)=>new Date(b.startDate)-new Date(a.startDate))[0];
  const [preview,setPreview]=useState(),[history,setHistory]=useState([]),[busy,setBusy]=useState(false),fileRef=useRef();
  const loadHistory=()=>api.listStudentRollovers().then(setHistory).catch(()=>setHistory([]));
  useEffect(()=>{loadHistory();},[]);
  const run=async(action)=>{setBusy(true);try{await action();}catch(error){notify(error.readableMessage||"Student rollover failed.","error");}finally{setBusy(false);}};
  if(!current||!source)return <div className="rollover-empty"><p>Create and activate a later Academic Session to prepare student rollover.</p></div>;
  return <div className="rollover-panel"><div className="rollover-heading"><div><h3>Student Rollover</h3><p>From <strong>{source.name}</strong> to <strong>{current.name}</strong></p></div><button type="button" disabled={busy} onClick={()=>run(async()=>setPreview(await api.prepareStudentRollover(source._id,current._id)))}>{busy?"Preparing…":"Prepare Student Rollover"}</button></div>
    {preview&&<div className="rollover-preview"><div className="rollover-summary">{Object.entries(preview.summary).map(([key,value])=><span key={key}><small>{labels[key]||key}</small><strong>{value}</strong></span>)}</div><div className="master-actions"><button type="button" onClick={()=>run(()=>api.downloadStudentRollover(preview.batchId))}>Download Rollover Excel</button><button type="button" onClick={()=>fileRef.current?.click()}>Upload Edited Excel</button><input ref={fileRef} hidden type="file" accept=".xlsx" onChange={(event)=>{const file=event.target.files?.[0];if(file)run(async()=>setPreview(await api.uploadStudentRollover(source._id,current._id,file)));event.target.value="";}}/><button type="button" disabled={busy||!preview.summary.suggestedUpdates} onClick={()=>run(async()=>{const result=await api.confirmStudentRollover(preview.batchId);notify(`${result.summary.updated||0} student(s) rolled over.`,"success");setPreview();await loadHistory();await onCompleted?.();})}>Confirm Rollover</button><button type="button" onClick={()=>setPreview()}>Cancel</button></div><div className="rollover-table"><table><thead><tr><th>Student ID</th><th>Student</th><th>Year</th><th>Status</th><th>Action</th></tr></thead><tbody>{preview.rows.slice(0,250).map((row,index)=><tr key={`${row.studentPublicId}-${index}`}><td>{row.studentPublicId||"Missing"}</td><td>{row.name}<small>{row.rollNumber}</small></td><td>{row.currentYear||"—"} → {row.proposedYear||"—"}</td><td>{row.currentStatus||"—"} → {row.proposedStatus||"—"}</td><td>{row.classification}{row.reasons?.length?<small>{row.reasons.join(", ")}</small>:null}</td></tr>)}</tbody></table>{preview.rows.length>250&&<p>Showing first 250 records. Download Excel to review the complete batch.</p>}</div></div>}
    {history.length>0&&<details className="rollover-history"><summary>Rollover History</summary>{history.map((item)=><div className="master-row" key={item.batchId}><span><strong>{item.batchId}</strong> · {item.fromSession} → {item.toSession} · {item.status}</span><small>{item.updated} updated · {item.reviewRequired} review · {item.skipped} skipped</small></div>)}</details>}
  </div>;
}
