const express = require("express");
const service = require("./academicSession.service");
const { authenticateSession } = require("../auth/auth.middleware");
const { requirePermission } = require("../authorization/authorization.middleware");
const multer = require("multer");
const rollover = require("./studentRollover.service");
const router = express.Router();
const ok = (res, data, status = 200) => res.status(status).json({ success: true, data });
const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 15 * 1024 * 1024 } }).single("file");
router.post("/rollovers/prepare", authenticateSession, requirePermission("session.edit"), async (req, res) => ok(res, await rollover.prepare({ ...req.body, actor: req.auth.userId }), 201));
router.post("/rollovers/upload", authenticateSession, requirePermission("session.edit"), upload, async (req, res) => { if (!req.file) return res.status(400).json({ success: false, error: { code: "INVALID_ROLLOVER_FILE", message: "XLSX file is required" } }); return ok(res, await rollover.upload({ ...req.body, file: req.file, actor: req.auth.userId }), 201); });
router.get("/rollovers/history", authenticateSession, requirePermission("session.view"), async (req, res) => ok(res, { items: await rollover.history() }));
router.get("/rollovers/:batchId/download", authenticateSession, requirePermission("session.view"), async (req, res) => { const buffer=await rollover.workbook(req.params.batchId);res.set({"Content-Type":"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","Content-Disposition":`attachment; filename="Student-Rollover-${req.params.batchId}.xlsx"`});res.send(buffer); });
router.post("/rollovers/:batchId/confirm", authenticateSession, requirePermission("session.edit"), async (req, res) => ok(res, await rollover.confirm(req.params.batchId, req.auth.userId)));
router.get("/current", authenticateSession, requirePermission("session.view"), async (req, res) => ok(res, { session: await service.getCurrentAcademicSession() }));
router.get("/", authenticateSession, requirePermission("session.view"), async (req, res) => ok(res, { items: await service.listSessions() }));
router.post("/", authenticateSession, requirePermission("session.create"), async (req, res) => ok(res, { session: await service.create(req.body, req.auth.userId) }, 201));
router.patch("/:id", authenticateSession, requirePermission("session.edit"), async (req, res) => ok(res, { session: await service.update(req.params.id, req.body, req.auth.userId) }));
router.post("/:id/set-current", authenticateSession, requirePermission("session.set_current"), async (req, res) => ok(res, { session: await service.setCurrent(req.params.id, req.auth.userId) }));
router.get("/:id", authenticateSession, requirePermission("session.view"), async (req, res) => ok(res, { session: await service.getSessionById(req.params.id) }));
module.exports = router;
