import {useCallback,useEffect,useRef,useState} from 'react'
import * as api from '../services/onboardingApi'
import {blankClaim,normalizeClaim} from '../utils/onboardingFormatters'
import {claimPayload,isValidClaim,validateClaim} from '../utils/onboardingValidation'

const messages={ONBOARDING_NOT_FOUND:'Your onboarding record has not been started.',ONBOARDING_NO_CLAIMS:'Add an existing society participation or submit a new society join request.',ONBOARDING_NOT_STARTED:'Start onboarding before submitting.',ONBOARDING_ALREADY_SUBMITTED:'Your onboarding has already been submitted.',ONBOARDING_STATE_INVALID:'This onboarding record can no longer be edited.',ONBOARDING_UNSAVED_CHANGES:'Save every society record before submitting.',CLAIM_NOT_FOUND:'This society record could not be found.',CLAIM_NOT_EDITABLE:'This society record can no longer be edited.',CLAIM_SOCIETY_REQUIRED:'Select a society.',CLAIM_ROLE_REQUIRED:'Select a role.',CLAIM_START_DATE_REQUIRED:'Select a start date.',CLAIM_END_DATE_REQUIRED:'Select an end date or mark the participation ongoing.',CLAIM_DATE_RANGE_INVALID:'An end date cannot be before its start date.',CLAIM_ROLE_INVALID:'Select a valid student society role.',CLAIM_SOCIETY_INVALID:'Select a valid active society.',CLAIM_DUPLICATE:'This society participation overlaps an existing record.',ONBOARDING_JOIN_REQUEST_REQUIRED:'Submit at least one society request before continuing.',MEMBERSHIP_REQUEST_REQUIRED:'Submit at least one society request before continuing.',MEMBERSHIP_REQUEST_EXISTS:'You already have a pending request for this society.',MEMBERSHIP_REQUEST_ALREADY_PENDING:'You already have a pending request for this society.',DUPLICATE_PENDING_REQUEST:'You already have a pending request for this society.',ALREADY_ACTIVE_MEMBER:'You are already an active member of this society.',MEMBERSHIP_ALREADY_ACTIVE:'You are already an active member of this society.',MEMBERSHIP_LIMIT_REACHED:'You have reached the maximum number of active societies.',VERIFICATION_ROUTE_UNAVAILABLE:'This society is not currently accepting membership requests because no authorized reviewer is available.'}
const safeMessage=error=>messages[error?.errorCode]||(error?.response?.status===401?'Your session has expired.':'Unable to complete onboarding. Please try again.')
const devLog=(operation,error)=>{if(import.meta.env.DEV)console.warn({operation,status:error?.response?.status,code:error?.errorCode,message:error?.readableMessage})}

export function useStudentOnboarding(){
  const[onboarding,setOnboarding]=useState(null),[student,setStudent]=useState(null),[claims,setClaims]=useState([]),[societies,setSocieties]=useState([]),[roles,setRoles]=useState([]),[undertakings,setUndertakings]=useState([]),[joinRequests,setJoinRequests]=useState([]),[choices,setChoices]=useState({existing:false,join:false}),[loading,setLoading]=useState(true),[loadError,setLoadError]=useState(''),[referenceError,setReferenceError]=useState(''),[saveState,setSaveState]=useState({status:'saved',message:''}),inFlight=useRef(new Set()),submitting=useRef(false),joining=useRef(false)
  const load=useCallback(async(force=false)=>{setLoading(true);setLoadError('');setReferenceError('');try{const{base,results}=await api.loadOnboardingPage(force),[progressResult,referencesResult,requiredResult,requestsResult]=results;if(progressResult.status==='rejected')throw progressResult.reason;const progress=progressResult.value,normalized=(progress.claims||[]).map(normalizeClaim);setOnboarding(progress.onboarding||base.onboarding);setStudent(base.student);setClaims(normalized);const failures=[];if(referencesResult.status==='fulfilled'){setSocieties(referencesResult.value.societies||[]);setRoles(referencesResult.value.roles||[])}else{devLog('load-onboarding-references',referencesResult.reason);failures.push('Society and role choices are unavailable.')}let persisted=[];if(requiredResult.status==='fulfilled')setUndertakings(requiredResult.value.items||[]);else{devLog('load-required-undertakings',requiredResult.reason);failures.push('Required undertakings could not be loaded.')}if(requestsResult.status==='fulfilled'){persisted=requestsResult.value.items||requestsResult.value.requests||[];setJoinRequests(persisted)}else{devLog('load-membership-requests',requestsResult.reason);failures.push('Saved membership requests could not be loaded.')}setChoices({existing:normalized.length>0,join:persisted.length>0});setReferenceError(failures.join(' '))}catch(error){devLog('initialize-onboarding',error);setLoadError(error?.response?.status===401?'Your session has expired.':'Unable to load onboarding details. Please try again.')}finally{setLoading(false)}},[])
  useEffect(()=>{load()},[load])
  const addClaim=()=>setClaims(items=>[...items,blankClaim()]),changeClaim=(localId,patch)=>setClaims(items=>items.map(item=>item.localId===localId?{...item,...patch,dirty:true}:item)),removeLocal=localId=>setClaims(items=>items.filter(item=>item.localId!==localId))
  const saveClaim=async localId=>{if(inFlight.current.has(localId))return null;const claim=claims.find(item=>item.localId===localId);if(!claim)return null;const errors=validateClaim(claim,claims);if(Object.keys(errors).length){setSaveState({status:'error',message:'Please correct the highlighted claim fields.'});return{errors}}inFlight.current.add(localId);setSaveState({status:'saving',message:''});try{const result=claim._id?await api.updateClaim(claim._id,claimPayload(claim)):await api.createClaim(claimPayload(claim)),saved=normalizeClaim(result.claim);setClaims(items=>items.map(item=>item.localId===localId?saved:item));setSaveState({status:'saved',message:''});return{claim:saved}}catch(error){devLog('save-claim',error);const message=safeMessage(error);setSaveState({status:'error',message});return{error:message}}finally{inFlight.current.delete(localId)}}
  const deleteDraft=async claim=>{if(inFlight.current.has(claim.localId))return false;if(!claim._id){removeLocal(claim.localId);return true}inFlight.current.add(claim.localId);try{await api.deleteClaim(claim._id);removeLocal(claim.localId);return true}catch(error){devLog('delete-claim',error);setSaveState({status:'error',message:safeMessage(error)});return false}finally{inFlight.current.delete(claim.localId)}}
  const acceptUndertaking=async id=>{try{await api.acceptUndertaking(id,'SIGNUP');setUndertakings(items=>items.map(item=>String(item._id)===String(id)?{...item,accepted:true}:item));return true}catch(error){devLog('accept-undertaking',error);setSaveState({status:'error',message:safeMessage(error)});return false}}
  const submitJoinRequest=async data=>{if(joining.current)return{ok:false};joining.current=true;try{const result=await api.createMembershipRequest(data);setJoinRequests(items=>[result.request,...items]);setChoices(value=>({...value,join:true}));setSaveState({status:'saved',message:''});return{ok:true,request:result.request}}catch(error){devLog('createMembershipRequest',error);const message=messages[error?.errorCode]||'Unable to submit this membership request. Please try again.';setSaveState({status:'error',message});return{ok:false,message}}finally{joining.current=false}}
  const refreshPersisted=async()=>{if(inFlight.current.size||claims.some(item=>item.dirty||!item._id)){setSaveState({status:'error',message:messages.ONBOARDING_UNSAVED_CHANGES});return false}try{const progress=await api.getOnboardingProgress(),persisted=(progress.claims||[]).map(normalizeClaim),localIds=new Set(claims.map(item=>String(item._id)));if(persisted.length!==claims.length||persisted.some(item=>!localIds.has(String(item._id)))){setSaveState({status:'error',message:messages.ONBOARDING_UNSAVED_CHANGES});return false}setOnboarding(progress.onboarding);setClaims(persisted);return true}catch(error){devLog('refresh-persisted',error);setSaveState({status:'error',message:safeMessage(error)});return false}}
  const submit=async()=>{if(submitting.current)return false;submitting.current=true;try{if(undertakings.some(item=>item.isMandatory&&!item.accepted)){setSaveState({status:'error',message:'Accept the mandatory undertaking before submitting.'});return false}if(claims.some(item=>!isValidClaim(item,claims))){setSaveState({status:'error',message:'Correct society record errors before submitting.'});return false}if(!(await refreshPersisted()))return false;const mode=claims.length&&joinRequests.length?'MIXED':claims.length?'EXISTING_PARTICIPATION':joinRequests.length?'NEW_JOIN_REQUEST':null;if(!mode){setSaveState({status:'error',message:messages.ONBOARDING_NO_CLAIMS});return false}setSaveState({status:'saving',message:''});await api.submitOnboarding(mode);setSaveState({status:'saved',message:''});return true}catch(error){devLog('submit',error);setSaveState({status:'error',message:safeMessage(error)});return false}finally{submitting.current=false}}
  return{onboarding,student,claims,societies,roles,undertakings,joinRequests,choices,setChoices,loading,loadError,referenceError,saveState,retry:()=>load(true),addClaim,changeClaim,saveClaim,deleteDraft,acceptUndertaking,submitJoinRequest,refreshPersisted,submit,isSubmitting:submitting.current,isSaving:inFlight.current.size>0}
}
