const crypto=require('crypto'),AppError=require('../../common/errors/AppError'),repo=require('./undertaking.repository'),{STATUSES,SCOPES}=require('./undertaking.constants')
const fail=(message,status,code)=>{throw new AppError(message,status,code)}
const activeFilter=scope=>({status:STATUSES.ACTIVE,isMandatory:true,scope:{$in:[scope,SCOPES.BOTH]},$and:[{$or:[{effectiveFrom:{$exists:false}},{effectiveFrom:{$lte:new Date()}}]},{$or:[{effectiveUntil:{$exists:false}},{effectiveUntil:{$gte:new Date()}}]}]})
const required=async(userId,scope=SCOPES.SIGNUP)=>{if(![SCOPES.SIGNUP,SCOPES.DASHBOARD_LOGIN].includes(scope))fail('Invalid undertaking scope',400,'UNDERTAKING_SCOPE_INVALID');const items=await repo.list(activeFilter(scope)),accepted=await repo.Acceptance.find({userId,undertakingId:{$in:items.map(x=>x._id)}}).lean(),keys=new Set(accepted.map(x=>`${x.undertakingId}:${x.undertakingVersion}`));return{items:items.map(x=>({...x,accepted:keys.has(`${x._id}:${x.version}`)}))}}
const create=async(data,actor)=>repo.create({...data,status:STATUSES.DRAFT,createdBy:actor,updatedBy:actor})
const get=async id=>{const item=await repo.get(id);if(!item)fail('Undertaking not found',404,'UNDERTAKING_NOT_FOUND');return item}
const update=async(id,data,actor)=>{const item=await get(id);if(item.status===STATUSES.ACTIVE&&data.version&&data.version!==item.version)fail('Active undertaking version cannot be edited',409,'UNDERTAKING_ACTIVE_VERSION_LOCKED');return repo.update(id,{...data,updatedBy:actor})}
const activate=async(id,actor)=>{const item=await get(id),now=new Date();if(item.effectiveUntil&&item.effectiveUntil<now)fail('Expired undertaking cannot be activated',409,'UNDERTAKING_EXPIRED');await repo.Undertaking.updateMany({_id:{$ne:item._id},scope:item.scope,version:item.version,status:STATUSES.ACTIVE},{$set:{status:STATUSES.INACTIVE,updatedBy:actor}});return repo.update(id,{status:STATUSES.ACTIVE,updatedBy:actor})}
const deactivate=(id,actor)=>update(id,{status:STATUSES.INACTIVE},actor)
const accept=async({id,user,student,scope,req})=>{const item=await get(id),available=await repo.Undertaking.exists({_id:id,...activeFilter(scope)});if(!available)fail('Undertaking is not active for this scope',409,'UNDERTAKING_NOT_ACTIVE');const ip=String(req.ip||'');const acceptance=await repo.accept({undertakingId:item._id,undertakingVersion:item.version,userId:user._id,studentMasterId:student?._id,acceptedAt:new Date(),scope,metadata:{ipHash:ip?crypto.createHash('sha256').update(ip).digest('hex'):undefined,userAgent:String(req.get('user-agent')||'').slice(0,500),sessionId:req.auth?.sessionId?String(req.auth.sessionId):undefined}});return{acceptance}}
module.exports={required,create,list:repo.list,get,update,activate,deactivate,accept,acceptances:repo.acceptances}
