import {useState} from 'react'
import {Bell,Building2,Plus,Trash2,Users} from 'lucide-react'
import {Avatar,Badge,Breadcrumb,Button,Card,Checkbox,ConfirmationDialog,Drawer,Dropdown,EmptyState,IconButton,Input,Modal,PageContainer,PageHeader,Pagination,Radio,SearchBox,Select,Skeleton,Spinner,StatCard,StatusChip,Switch,Table,Textarea,ToastProvider,Tooltip,useDesignToast} from './index'

const rows=[{id:'1',name:'Fine Arts Society',status:'Active',members:128},{id:'2',name:'Entrepreneurship Cell',status:'Pending',members:84},{id:'3',name:'Music Society',status:'Active',members:96}]
function Showcase(){const[modal,setModal]=useState(null),[drawer,setDrawer]=useState(false),[confirm,setConfirm]=useState(false),[selected,setSelected]=useState([]),[query,setQuery]=useState(''),[page,setPage]=useState(1),toast=useDesignToast();const filtered=rows.filter(x=>x.name.toLowerCase().includes(query.toLowerCase()));return <PageContainer><PageHeader eyebrow="Developer reference" title="Campus Connect Design System" description="Reusable, accessible foundations for every Society Portal experience." breadcrumb={<Breadcrumb items={[{label:'Admin',href:'/admin'},{label:'Design System'}]}/>} actions={<Button icon={Plus}>Create action</Button>}/>
<section className="showcase-grid showcase-stats"><StatCard icon={Users} value="15,240" label="Students" change="+4.2% this session"/><StatCard icon={Building2} value="42" label="Active societies"/><StatCard icon={Bell} value="8" label="Pending reviews"/></section>
<Card title="Typography & color" description="Compact type hierarchy and Campus Connect premium palette."><div className="type-demo"><h1>Dashboard title · 28px</h1><h2>Page title · 22px</h2><h3>Card title · 18px</h3><p>Normal body copy · 14px</p><small>Helper text · 13px</small></div><div className="color-grid">{[['Background','#FAFAFB'],['Surface','#FFFFFF'],['TIET Maroon','#86172C'],['Text','#25262D'],['Success','#287A55'],['Warning','#93621C']].map(([n,c])=><div key={n}><i style={{background:c}}/><b>{n}</b><span>{c}</span></div>)}</div></Card>
<Card title="Buttons" description="Outlined maroon is the default. Filled maroon is reserved for critical confirmation."><div className="showcase-row"><Button>Primary</Button><Button variant="outline">Outline</Button><Button variant="secondary">Secondary</Button><Button variant="ghost">Ghost</Button><Button variant="danger" icon={Trash2}>Danger</Button><Button variant="success">Success</Button><Button loading>Loading</Button><IconButton label="Notifications"><Bell size={17}/></IconButton></div></Card>
<section className="showcase-grid"><Card title="Form controls"><div className="form-demo"><Input label="Society name" placeholder="Enter society name" helper="Use the official registered name."/><Textarea label="Description" placeholder="Add a short description"/><Select label="Category" options={['Technical','Cultural','Social']}/><SearchBox value={query} onChange={e=>setQuery(e.target.value)}/><div className="showcase-row"><Checkbox label="Selected" defaultChecked/><Radio label="Option A" name="option" defaultChecked/><Radio label="Option B" name="option"/><Switch label="Enabled" defaultChecked/></div></div></Card><Card title="Badges, identity & utilities"><div className="showcase-row"><Badge>Neutral</Badge><Badge tone="info">Information</Badge><StatusChip status="Active"/><StatusChip status="Pending"/><StatusChip status="Rejected"/></div><div className="showcase-row"><Avatar name="Aarav Sharma" size="sm"/><Avatar name="Aarav Sharma"/><Avatar name="Aarav Sharma" size="lg"/><Tooltip content="Helpful context"><Button variant="ghost">Hover for tooltip</Button></Tooltip><Dropdown items={[{label:'View details'},{label:'Edit record'},{label:'Archive'}]}/></div></Card></section>
<Card title="Table system" description="Sticky heading, search, sorting, bulk selection, pagination, empty and loading states." actions={<SearchBox value={query} onChange={e=>setQuery(e.target.value)}/>}><Table selectable selected={selected} onSelectionChange={setSelected} columns={[{key:'name',label:'Society',sortable:true},{key:'status',label:'Status',render:v=><StatusChip status={v}/>},{key:'members',label:'Members',sortable:true}]} rows={filtered}/><div className="table-footer"><span>{selected.length} selected</span><Pagination page={page} totalPages={4} onChange={setPage}/></div></Card>
<section className="showcase-grid"><Card title="Loading"><div className="showcase-row"><Spinner/><span>Loading records…</span></div><Skeleton lines={4}/></Card><Card title="Empty state"><EmptyState title="No societies found" description="New records will appear here." action={<Button icon={Plus}>Add society</Button>}/></Card></section>
<Card title="Overlays & feedback"><div className="showcase-row"><Button onClick={()=>setModal('sm')}>Small modal</Button><Button onClick={()=>setModal('md')}>Medium modal</Button><Button onClick={()=>setModal('lg')}>Large modal</Button><Button onClick={()=>setModal('full')}>Fullscreen modal</Button><Button variant="secondary" onClick={()=>setDrawer(true)}>Open drawer</Button><Button variant="danger" onClick={()=>setConfirm(true)}>Confirmation</Button><Button variant="success" onClick={()=>toast('Changes saved successfully','success')}>Show toast</Button></div></Card>
<Modal open={!!modal} onClose={()=>setModal(null)} size={modal} title={`${modal?.toUpperCase()} modal`} footer={<><Button variant="ghost" onClick={()=>setModal(null)}>Cancel</Button><Button onClick={()=>setModal(null)}>Save changes</Button></>}><p>Reusable modal content with accessible dialog semantics and Escape-key dismissal.</p></Modal><Drawer open={drawer} onClose={()=>setDrawer(false)} title="Details drawer"><p>Contextual content without leaving the current page.</p></Drawer><ConfirmationDialog open={confirm} onClose={()=>setConfirm(false)} onConfirm={()=>{setConfirm(false);toast('Record removed','danger')}} danger title="Remove this record?" description="This action should only be used for destructive operations." confirmLabel="Remove"/>
</PageContainer>}
export default function DesignSystemShowcase(){return <ToastProvider><Showcase/></ToastProvider>}
