import { AlertCircle, ArrowRight, Bell, CalendarPlus, CheckCircle2, Clock3, ClipboardList, UserRound, UsersRound } from "lucide-react";
import { useNavigate, useOutletContext } from "react-router-dom";
import { Badge, Button, Card, EmptyState, Skeleton, StatCard } from "../../../design-system";
import { ProfileAvatar } from "../../../components/app-shell/AppShell";
import { useAuth } from "../hooks/useAuth";
import { useStudentPortalData } from "../hooks/useStudentPortalData";
import "./student-home.css";

const hasPermission = (context, code) => (context?.permissions || []).some((item) => (item.code || item) === code);
export default function StudentHomePage() {
  const auth = useAuth(), navigate = useNavigate(), { selectedContext } = useOutletContext(), data = useStudentPortalData();
  if (data.loading) return <div className="student-home-loading"><Skeleton lines={8} /></div>;
  if (data.error) return <EmptyState icon={AlertCircle} title="Dashboard unavailable" description={data.error} action={<Button variant="outline" onClick={data.refresh}>Try again</Button>} />;
  const pendingItems = data.requests.filter((x) => ["SUBMITTED", "PENDING", "ASSIGNED"].includes(x.status)), attentionRequests = data.requests.filter((x) => x.status === "CLARIFICATION_REQUESTED"), attentionClaims = data.claims.filter((x) => ["CHANGES_REQUESTED", "RESUBMISSION_ALLOWED"].includes(x.status)), attention = attentionRequests.length + attentionClaims.length, hour = new Date().getHours(), greeting = hour < 12 ? "Good morning" : hour < 17 ? "Good afternoon" : "Good evening", canCreateEvent = hasPermission(selectedContext, "event.create"), roles = [...new Set((auth.activeSocietyContexts || []).map((item) => item.roleName).filter(Boolean))];
  const quickActions = [
    ...(auth.membership?.joinSocietyAvailable ? [{ label: "Join Society", detail: "Find your community", icon: UsersRound, route: "/student/societies" }] : []),
    { label: "My Societies", detail: "Memberships & roles", icon: UsersRound, route: "/student/societies" },
    ...(canCreateEvent ? [{ label: "Create Event", detail: selectedContext?.societyName, icon: CalendarPlus, route: "/student/events/new" }] : []),
    { label: "Requests", detail: "Track your status", icon: ClipboardList, route: "/student/requests" },
    { label: "Notifications", detail: "Portal updates", icon: Bell, route: "/student/notifications" },
    { label: "Profile", detail: "Personal information", icon: UserRound, route: "/student/profile" },
  ];
  return <div className="student-home">
    <section className="student-welcome-card"><div><span className="student-welcome-card__eyebrow">{greeting}</span><h1>{auth.user?.displayName || "Student"}</h1><p>{auth.student?.rollNumber || "TIET Student"}{auth.student?.department ? ` · ${auth.student.department}` : ""}</p><div className="student-welcome-card__tags">{roles.slice(0, 3).map((role) => <span key={role}>{role}</span>)}</div></div><ProfileAvatar user={auth.user} size="lg" /></section>
    {!selectedContext && <Card className="student-onboarding-card"><div className="student-onboarding-card__icon"><UsersRound /></div><div><Badge tone="warning">Membership</Badge><h2>Your society journey starts here</h2><p>You don’t have an active society membership yet. Browse societies or follow an existing request.</p><div className="student-action-row">{auth.membership?.joinSocietyAvailable && <Button onClick={() => navigate("/student/societies")}>Join a Society</Button>}{data.requests.length > 0 && <Button variant="outline" onClick={() => navigate("/student/requests")}>View Requests</Button>}</div></div></Card>}
    <div className="student-stat-grid"><StatCard icon={UsersRound} label="Active Societies" value={data.memberships.length} /><StatCard icon={Clock3} label="Pending Requests" value={pendingItems.length} /><StatCard icon={AlertCircle} label="Needs Attention" value={attention} /></div>
    {(attention > 0 || pendingItems.length > 0) && <section className="student-home-section"><div className="student-section-heading"><div><span>Keep things moving</span><h2>Pending & action required</h2></div><Button variant="ghost" onClick={() => navigate("/student/requests")}>View all <ArrowRight size={16} /></Button></div><div className="student-attention-list">{attention > 0 && <button onClick={() => navigate("/student/requests")}><span className="is-danger"><AlertCircle /></span><div><strong>{attention} item{attention === 1 ? "" : "s"} need your response</strong><small>Clarification or correction requested</small></div><ArrowRight /></button>}{pendingItems.length > 0 && <button onClick={() => navigate("/student/requests")}><span className="is-warning"><Clock3 /></span><div><strong>{pendingItems.length} request{pendingItems.length === 1 ? "" : "s"} under review</strong><small>We’ll reflect decisions here when available</small></div><ArrowRight /></button>}</div></section>}
    <section className="student-home-section"><div className="student-section-heading"><div><span>Your memberships</span><h2>My societies</h2></div>{auth.activeSocietyContexts?.length > 0 && <Button variant="ghost" onClick={() => navigate("/student/societies")}>View all <ArrowRight size={16} /></Button>}</div>{auth.activeSocietyContexts?.length ? <div className="student-membership-scroll">{auth.activeSocietyContexts.map((context) => <button className={context.id === selectedContext?.id ? "active" : ""} key={context.id} onClick={() => navigate("/student/societies")}><span><UsersRound /></span><div><strong>{context.societyName}</strong><small>{context.roleName}</small></div>{context.id === selectedContext?.id && <CheckCircle2 className="student-membership-check" />}</button>)}</div> : <EmptyState icon={UsersRound} title="No active societies" description="Approved memberships will appear here." />}</section>
    <section className="student-home-section"><div className="student-section-heading"><div><span>Shortcuts</span><h2>Quick actions</h2></div></div><div className="student-quick-grid">{quickActions.map(({ label, detail, icon: Icon, route }) => <button key={label} onClick={() => navigate(route)}><span><Icon /></span><div><strong>{label}</strong><small>{detail}</small></div><ArrowRight /></button>)}</div></section>
    <section className="student-home-section"><div className="student-section-heading"><div><span>Latest updates</span><h2>Recent activity</h2></div></div><EmptyState icon={ClipboardList} title="No recent activity to show" description="Your existing requests and memberships are available in their dedicated sections." /></section>
  </div>;
}
