import {useCallback,useEffect,useState} from 'react'
import {ArrowRight,CheckCircle2,Clock3,RotateCcw,XCircle} from 'lucide-react'
import {useNavigate} from 'react-router-dom'
import {Badge,Button,Card,EmptyState,PageContainer,PageHeader,Skeleton,StatCard,StatusChip} from '../../../design-system'
import {getOnboardingProgress,listMyMembershipRequests,resubmitClaim} from '../../onboarding/services/onboardingApi'
import {useToast} from '../../../components/common/toastContext'
import {useAuth} from '../hooks/useAuth'
import './student-verification.css'
const fmt=v=>v?new Date(v).toLocaleDateString():'—',routeLabel={SOCIETY_HIGHER_ROLE_REVIEW:'Society Leadership Review',SOCIETY_TEAM_REVIEW:'Society Team Review',GENERAL_SECRETARY:'Society Team Review',PRESIDENT_OR_VICE_PRESIDENT:'Society Leadership Review',SUPER_ADMIN_FALLBACK:'Campus Administration Review'}
export default function StudentVerificationPage(){
  const navigate=useNavigate(),auth=useAuth(),{notify}=useToast(),[data,setData]=useState(null),[requests,setRequests]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState('')
  const load=useCallback(async()=>{setLoading(true);setError('');try{const[p,r]=await Promise.all([getOnboardingProgress(),listMyMembershipRequests()]);setData(p);setRequests(r.items||[])}catch(e){setError(e.readableMessage)}finally{setLoading(false)}},[])
  useEffect(()=>{load()},[load])
  if(loading)return <main className="student-verification"><Skeleton lines={10}/></main>
  if(error)return <main className="student-verification"><EmptyState title="Verification status unavailable" description={error} action={<Button onClick={load}>Retry</Button>}/></main>
  const s=data.summary||{},dashboardAllowed=s.approvedClaims>0&&(auth.onboarding?.nextAction==='DASHBOARD'||auth.activeSocietyContexts.length>0)
  const goDashboard=async()=>{try{const fresh=await auth.loadCurrentUser();if(fresh?.nextAction==='DASHBOARD'||fresh?.activeSocietyContexts?.length)navigate('/student/dashboard');else notify('Dashboard access is not available yet.','warning')}catch(e){notify(e.readableMessage,'error')}}
  return <main className="student-verification"><PageContainer><PageHeader eyebrow="TIET Society Portal" title="Profile Verification" description="Track each society claim and review outcome." actions={dashboardAllowed?<Button icon={ArrowRight} onClick={goDashboard}>Go to Dashboard</Button>:null}/><Card className="verification-hero"><Clock3/><div><h2>Your society profile is under review.</h2><p>Approved, pending and correction-required claims are shown separately below.</p></div></Card><div className="verification-summary"><StatCard label="Total Claims" value={s.totalClaims||0}/><StatCard label="Approved" value={s.approvedClaims||0}/><StatCard label="Pending" value={s.pendingClaims||0}/><StatCard label="Rejected / Correction" value={(s.rejectedClaims||0)+(s.lockedClaims||0)}/></div><section className="verification-list"><h2>Existing participation</h2>{data.claims?.map(c=><ClaimCard key={c._id} claim={c} navigate={navigate} onResubmit={async()=>{try{await resubmitClaim(c._id);notify('Claim submitted for re-evaluation.','success');load()}catch(e){notify(e.readableMessage,'error')}}}/>)}</section>{requests.length>0&&<section className="verification-list"><h2>Join society requests</h2>{requests.map(r=><Card key={r._id} title={r.societyId?.name||'Society request'} actions={<StatusChip status={r.status}/>}><p>Requested role: Member</p><p>{r.requestReason}</p>{r.decisionReason&&<p className="verification-reason"><b>Reviewer response:</b> {r.decisionReason}</p>}</Card>)}</section>}</PageContainer></main>
}
export function ClaimCard({claim,navigate,onResubmit}){const correction=claim.status==='RESUBMISSION_ALLOWED'||claim.status==='CHANGES_REQUESTED',rejected=claim.status==='REJECTED'||claim.status==='LOCKED',approved=claim.status==='APPROVED';return <Card className="verification-claim"><header><div><h3>{claim.society?.name}</h3><p>{claim.role?.name}</p></div><StatusChip status={correction?'CHANGES REQUESTED':claim.status}/></header><div className="verification-claim-meta"><span><small>Duration</small>{fmt(claim.startDate)} — {claim.isOngoing?'Present':fmt(claim.endDate)}</span><span><small>Attempt</small>{claim.attemptNumber}</span>{claim.status==='PENDING'&&<span><small>Currently reviewing</small>{routeLabel[claim.verificationRouteType]||'Assigned reviewer'}</span>}</div>{claim.rejectionReason&&<p className="verification-reason"><b>{correction?'Correction requested:':'Reason:'}</b> {claim.rejectionReason}</p>}<ol className="verification-timeline"><li className="done">Submitted</li><li className="done">Assigned for Review</li><li className={claim.decisionAt?'done':''}>Reviewed</li><li className={approved?'approved':rejected||correction?'rejected':''}>{approved?'Approved':correction?'Changes Requested':rejected?'Rejected':'Awaiting decision'}</li></ol><div className="verification-card-actions">{correction&&<Button icon={ArrowRight} onClick={()=>navigate(`/student/onboarding/correction/${claim._id}`)}>Correct Details</Button>}{rejected&&claim.canResubmit&&<Button icon={RotateCcw} onClick={onResubmit}>Request Re-evaluation</Button>}{approved&&<Badge tone="success"><CheckCircle2 size={14}/>Verified</Badge>}{claim.status==='PENDING'&&<Badge tone="warning"><Clock3 size={14}/>Review in progress</Badge>}{rejected&&!claim.canResubmit&&<Badge tone="danger"><XCircle size={14}/>Review complete</Badge>}</div></Card>}
