import {useState} from 'react'
import {Plus} from 'lucide-react'
import {Button,Card,EmptyState,Modal,PageHeader,Skeleton,StatusChip} from '../../../design-system'
import {useToast} from '../../../components/common/toastContext'
import JoinSocietyForm from '../../onboarding/components/JoinSocietyForm'
import {createMembershipRequest} from '../../onboarding/services/onboardingApi'
import {useAuth} from '../hooks/useAuth'
import {useStudentPortalData} from '../hooks/useStudentPortalData'
export default function StudentSocietiesPage(){const auth=useAuth(),{notify}=useToast(),data=useStudentPortalData(),[open,setOpen]=useState(false);if(data.loading)return <Skeleton lines={8}/>;const submit=async payload=>{try{await createMembershipRequest(payload);notify('Membership request submitted.','success');setOpen(false);await data.refresh();return{ok:true}}catch(e){return{ok:false,message:e.readableMessage||'Unable to submit this membership request. Please try again.'}}};const requested=data.requests.filter(x=>['SUBMITTED','PENDING','ASSIGNED','CLARIFICATION_REQUESTED'].includes(x.status));return <><PageHeader eyebrow="Student Portal" title="My Societies" description="Active memberships and requested societies are kept separate." actions={<Button icon={Plus} onClick={()=>setOpen(true)}>Join Another Society</Button>}/><section className="portal-section"><h2>Active Societies</h2><div className="student-society-grid">{data.memberships.length?data.memberships.map(item=><Card key={item._id} title={item.societyId?.name||'Society'} actions={<StatusChip status="ACTIVE"/>}><p>{item.roleId?.name||item.roleName}</p></Card>):<EmptyState title="No active society memberships" description="Approved requests will appear here."/>}</div></section><section className="portal-section"><h2>Requested Societies</h2><div className="student-society-grid">{requested.length?requested.map(item=><Card key={item._id} title={item.societyId?.name||'Society'} actions={<StatusChip status={item.status}/>}><p>{item.requestReason}</p></Card>):<EmptyState title="No pending society requests"/>}</div></section><Modal open={open} onClose={()=>setOpen(false)} title="Join Another Society"><JoinSocietyForm societies={data.societies} requests={data.requests} activeSocietyIds={(auth.activeSocietyContexts||[]).map(x=>x.societyId)} onSubmit={submit}/></Modal></>}
