import apiClient from '../../../services/apiClient'
const data=r=>r.data.data
export const listUsers=(params={})=>apiClient.get('/users',{params}).then(data)
export const getUser=id=>apiClient.get(`/users/${id}`).then(r=>data(r).user)
export const createUser=payload=>apiClient.post('/users',payload).then(r=>data(r).user)
export const updateUser=(id,payload)=>apiClient.patch(`/users/${id}`,payload).then(r=>data(r).user)
export const changeUserStatus=(id,status,reason='Updated by administrator')=>apiClient.patch(`/users/${id}/status`,{status,reason}).then(r=>data(r).user)
export const changeLoginAccess=(id,isLoginAllowed,reason='Updated by administrator')=>apiClient.patch(`/users/${id}/login-access`,{isLoginAllowed,reason}).then(r=>data(r).user)
export const listRoles=(params={})=>apiClient.get('/roles',{params}).then(data)
export const listActiveDepartments=()=>apiClient.get('/departments/lookup').then(r=>data(r).items)
export const listRoleOverview=(params={})=>apiClient.get('/roles/admin-overview',{params}).then(data)
export const getRole=id=>apiClient.get(`/roles/${id}`).then(r=>data(r).role)
export const createRole=payload=>apiClient.post('/roles',payload).then(r=>data(r).role)
export const updateRole=(id,payload)=>apiClient.patch(`/roles/${id}`,payload).then(r=>data(r).role)
export const changeRoleStatus=(id,status)=>apiClient.patch(`/roles/${id}/status`,{status}).then(r=>data(r).role)
export const listPermissions=(params={})=>apiClient.get('/permissions',{params}).then(data)
export const getPermissionCatalog=()=>apiClient.get('/permissions/catalog/grouped').then(r=>data(r).catalog)
export const getRolePermissions=id=>apiClient.get(`/roles/${id}/permissions`).then(r=>data(r).permissions)
export const replaceRolePermissions=(id,permissions)=>apiClient.put(`/roles/${id}/permissions`,{permissions}).then(data)
export const previewPermissionSync=()=>apiClient.get('/permissions/sync/preview').then(data)
export const confirmPermissionSync=()=>apiClient.post('/permissions/sync/confirm').then(data)
export const getUserEffectivePermissions=id=>apiClient.get(`/users/${id}/effective-permissions`).then(data)
export const listAssignments=(params={})=>apiClient.get('/user-role-assignments',{params}).then(data)
export const activeAssignments=id=>apiClient.get(`/user-role-assignments/user/${id}/active`).then(r=>data(r).assignments)
export const downloadUserTemplate=()=>apiClient.get('/users/import/template',{responseType:'blob'}).then(response=>response.data)
export const previewUserImport=file=>{const body=new FormData();body.append('file',file);return apiClient.post('/users/import/preview',body).then(data)}
export const confirmUserImport=id=>apiClient.post(`/users/import/${id}/confirm`).then(data)
export const assignRole=payload=>apiClient.post('/user-role-assignments',payload).then(r=>data(r).assignment)
export const updateAssignment=(id,payload)=>apiClient.patch(`/user-role-assignments/${id}`,payload).then(r=>data(r).assignment)
export const finishAssignment=(id,action='end')=>apiClient.patch(`/user-role-assignments/${id}/${action}`,{remarks:`${action==='end'?'Ended':'Revoked'} by administrator`}).then(r=>data(r).assignment)
export const exportUserRows=rows=>{const keys=['displayName','email','accountType','department','designation','isLoginAllowed','status'];const esc=v=>`"${String(v??'').replaceAll('"','""')}"`;const csv=[keys.join(','),...rows.map(u=>[u.displayName,u.email,u.accountType,u.metadata?.department,u.metadata?.designation,u.isLoginAllowed,u.status].map(esc).join(','))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='portal-users.csv';a.click();URL.revokeObjectURL(a.href)}
