import { useRef, useState } from 'react'
import { motion } from 'framer-motion'
import { FileSpreadsheet, LoaderCircle, X } from 'lucide-react'
import AppButton from '../../../components/common/AppButton'
import AppInput from '../../../components/common/AppInput'
import { confirmImport, getImportSession, previewImport } from '../../../services/societyImportApi'
import { useToast } from '../../../components/common/toastContext'

export default function ImportSocietiesModal({open,onClose,onImportCompleted}){
  const[file,setFile]=useState(null);const[session,setSession]=useState('');const[preview,setPreview]=useState(null);const[result,setResult]=useState(null);const[isPreviewing,setIsPreviewing]=useState(false);const[isConfirming,setIsConfirming]=useState(false);const confirmingRef=useRef(false);const{notify}=useToast()
  if(!open)return null
  const importableCount=preview?.rows.filter(row=>row.importable&&row.action!=='SKIP'&&row.errors.length===0).length||0
  const complete=(data,{recovered=false}={})=>{setResult(data);onImportCompleted?.();if(recovered)notify('This import was already completed successfully.','info');else{const created=data.summary?.societiesCreated||0;notify(created?`${created} societies imported successfully`:'No societies were created; all rows were skipped or failed.',created?'success':'warning')}}
  const doPreview=async()=>{if(isPreviewing||isConfirming)return;if(!file)return notify('Select an XLSX file','warning');if(file.size>5*1024*1024)return notify('File must not exceed 5 MB','warning');if(!session.trim())return notify('Enter an academic session','warning');setIsPreviewing(true);try{setPreview(await previewImport(file,session));setResult(null);notify('Preview generated','success')}catch(e){notify(e.readableMessage,'error')}finally{setIsPreviewing(false)}}
  const confirm=async()=>{
    if(confirmingRef.current||isConfirming||result||!preview||importableCount===0)return
    confirmingRef.current=true;setIsConfirming(true)
    try{complete(await confirmImport(preview.importSessionId))}
    catch(error){
      if(error.errorCode==='IMPORT_SESSION_ALREADY_USED'){
        try{const stored=await getImportSession(preview.importSessionId);if(stored.status==='IMPORTED'&&stored.importSummary&&stored.importResults){complete({importSessionId:stored.importSessionId,status:stored.status,summary:stored.importSummary,results:stored.importResults},{recovered:true});return}}catch{ /* Show the original confirmation error below. */ }
      }
      notify(error.readableMessage,'error')
    }finally{confirmingRef.current=false;setIsConfirming(false)}
  }
  const reset=()=>{if(isConfirming)return;setFile(null);setSession('');setPreview(null);setResult(null)}
  const close=()=>{if(isConfirming)return;reset();onClose()}
  return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&close()}><motion.div className="modal" role="dialog" aria-modal="true" aria-labelledby="import-title" initial={{y:60,opacity:0}} animate={{y:0,opacity:1}}><div className="modal-header"><h2 id="import-title">Import Societies</h2><button type="button" className="icon-button" aria-label="Close" disabled={isConfirming} onClick={close}><X/></button></div>{!preview&&<div className="page-stack"><div className="card"><FileSpreadsheet size={28}/><div className="field"><label htmlFor="xlsx">XLSX file</label><input id="xlsx" className="input" type="file" disabled={isPreviewing} accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" onChange={e=>setFile(e.target.files[0]||null)}/></div></div><AppInput id="import-session" label="Academic Session" placeholder="2026-27" disabled={isPreviewing} value={session} onChange={e=>setSession(e.target.value)}/><AppButton type="button" onClick={doPreview} disabled={isPreviewing}>{isPreviewing?<><LoaderCircle className="spinner" size={17}/>Generating…</>:'Generate Preview'}</AppButton></div>}{preview&&!result&&<div className="page-stack"><Summary summary={preview.summary}/><div className="preview-cards society-list">{preview.rows.map(row=><PreviewCard key={row.rowNumber} row={row}/>)}</div><PreviewTable rows={preview.rows}/><div className="card-actions"><AppButton type="button" onClick={confirm} disabled={isConfirming||importableCount===0}>{isConfirming?<><LoaderCircle className="spinner" size={17}/>Importing {importableCount} Rows...</>:`Confirm ${importableCount} Importable Rows`}</AppButton><AppButton type="button" variant="ghost" disabled={isConfirming} onClick={()=>setPreview(null)}>Choose another file</AppButton></div>{importableCount===0&&<p className="muted">There are no importable rows to confirm. Review warnings and errors above.</p>}</div>}{result&&<div className="page-stack"><h3>Import complete</h3><Summary summary={result.summary}/>{result.results&&<div className="society-list">{result.results.map(row=><div className="card" key={row.rowNumber}><strong>{row.societyName}</strong><p className="muted">Society: {row.societyStatus} · Leadership: {row.leadershipStatus}</p>{row.errors?.length>0&&<ul className="issue-list">{row.errors.map(error=><li key={error}>{error}</li>)}</ul>}</div>)}</div>}<div className="card-actions"><AppButton type="button" disabled>Import Completed</AppButton><AppButton type="button" variant="secondary" onClick={reset}>Upload Another File</AppButton><AppButton type="button" variant="ghost" onClick={close}>Close</AppButton></div></div>}</motion.div></div>
}

function PreviewCard({row}){return <div className="card preview-row"><div className="society-top"><strong>Row {row.rowNumber}: {row.name||'Unnamed'}</strong><span className="badge">{row.action}</span></div><div className="preview-details"><div><span>Generated code</span><strong>{row.code||'—'}</strong></div><div><span>Official email</span><strong>{row.officialEmail||'—'}</strong></div><div><span>Entity type</span><strong>{row.entityType||'—'}</strong></div><div><span>Campus</span><strong>{row.campus||'—'}</strong></div></div><Issues row={row}/></div>}
function PreviewTable({rows}){return <div className="preview-table table-wrap"><table><thead><tr><th>Row</th><th>Society</th><th>Code</th><th>Official Email</th><th>Entity Type</th><th>Campus</th><th>Action</th><th>Issues</th></tr></thead><tbody>{rows.map(row=><tr key={row.rowNumber}><td>{row.rowNumber}</td><td>{row.name||'—'}</td><td>{row.code||'—'}</td><td>{row.officialEmail||'—'}</td><td>{row.entityType||'—'}</td><td>{row.campus||'—'}</td><td>{row.action}</td><td><Issues row={row}/></td></tr>)}</tbody></table></div>}
function Issues({row}){const issues=[...row.warnings,...row.errors];return issues.length?<ul className="issue-list">{issues.map(issue=><li key={issue}>{issue.replaceAll('_',' ')}</li>)}</ul>:<span className="muted">None</span>}
function Summary({summary}){return <div className="stats-grid">{Object.entries(summary).map(([key,value])=><div className="card stat-card" key={key}><div className="stat-value">{value}</div><div className="stat-label">{key.replace(/([A-Z])/g,' $1').replace(/^./,c=>c.toUpperCase())}</div></div>)}</div>}
