import apiClient from "../../../services/apiClient";
const arrayAt = (response, key) => {
  const value = response?.data?.data?.[key];
  if (Array.isArray(value)) return value;
  if (value === undefined || value === null) return [];
  const error = new Error(`Unexpected ${key} response`);
  error.readableMessage = `The server returned an invalid ${key} response.`;
  error.errorCode = "INVALID_API_RESPONSE";
  throw error;
};
export const getSettings = async () => arrayAt(await apiClient.get("/portal-settings"), "settings");
export const updateSetting = async (key, value) => (await apiClient.patch(`/portal-settings/${key}`, { value })).data.data;
export const listSessions = async () => arrayAt(await apiClient.get("/academic-sessions"), "items");
export const createSession = async (data) => (await apiClient.post("/academic-sessions", data)).data.data;
export const updateSession = async (id, data) => (await apiClient.patch(`/academic-sessions/${id}`, data)).data.data;
export const setCurrentSession = async (id) => (await apiClient.post(`/academic-sessions/${id}/set-current`)).data.data;
export const prepareStudentRollover = async (sourceSessionId, targetSessionId) => (await apiClient.post("/academic-sessions/rollovers/prepare", { sourceSessionId, targetSessionId })).data.data;
export const uploadStudentRollover = async (sourceSessionId, targetSessionId, file) => { const form = new FormData(); form.append("sourceSessionId", sourceSessionId); form.append("targetSessionId", targetSessionId); form.append("file", file); return (await apiClient.post("/academic-sessions/rollovers/upload", form)).data.data; };
export const confirmStudentRollover = async (batchId) => (await apiClient.post(`/academic-sessions/rollovers/${batchId}/confirm`)).data.data;
export const listStudentRollovers = async () => arrayAt(await apiClient.get("/academic-sessions/rollovers/history"), "items");
export const downloadStudentRollover = async (batchId) => { const response=await apiClient.get(`/academic-sessions/rollovers/${batchId}/download`,{responseType:"blob"}),url=URL.createObjectURL(response.data),link=document.createElement("a");link.href=url;link.download=`Student-Rollover-${batchId}.xlsx`;link.click();URL.revokeObjectURL(url); };
export const listDepartments = async () => arrayAt(await apiClient.get("/departments"), "items");
export const saveDepartment = async (data) => (await apiClient.post("/departments", data)).data.data;
export const updateDepartment = async (id, data) => (await apiClient.patch(`/departments/${id}`, data)).data.data;
export const listBuildings = async () => arrayAt(await apiClient.get("/infrastructure/buildings"), "items");
export const saveBuilding = async (data) => (await apiClient.post("/infrastructure/buildings", data)).data.data;
export const updateBuilding = async (id, data) => (await apiClient.patch(`/infrastructure/buildings/${id}`, data)).data.data;
export const listVenues = async () => arrayAt(await apiClient.get("/infrastructure/venues"), "items");
export const saveVenue = async (data) => (await apiClient.post("/infrastructure/venues", data)).data.data;
export const updateVenue = async (id, data) => (await apiClient.patch(`/infrastructure/venues/${id}`, data)).data.data;
const importBase = { department: "/departments/import", building: "/infrastructure/buildings/import", venue: "/infrastructure/venues/import" };
export const downloadMasterTemplate = async (type) => { const response = await apiClient.get(`${importBase[type]}/template`, { responseType: "blob" }), url = URL.createObjectURL(response.data), link = document.createElement("a"); link.href = url; link.download = `${type}-import-template.xlsx`; link.click(); URL.revokeObjectURL(url); };
export const previewMasterImport = async (type, file) => { const form = new FormData(); form.append("file", file); return (await apiClient.post(`${importBase[type]}/preview`, form)).data.data; };
export const confirmMasterImport = async (type, id) => (await apiClient.post(`${importBase[type]}/${id}/confirm`)).data.data;
