const express = require("express");
const mongoose = require("mongoose");
const AppError = require("../../common/errors/AppError");
const Department = require("./department.model");
const { authenticateSession } = require("../auth/auth.middleware");
const { requirePermission } = require("../authorization/authorization.middleware");
const imports = require("../masterImports/masterImport.service"), importValidation = require("../masterImports/masterImport.validation");
const router = express.Router(), ok = (res, data, status = 200) => res.status(status).json({ success: true, data });
const cache=require("../../cache/cacheService"),keys=require("../../cache/cacheKeys"),ttl=require("../../cache/cacheTtls"),invalidate=require("../../cache/cacheInvalidation");
router.use((req,res,next)=>{if(["POST","PATCH","PUT","DELETE"].includes(req.method))res.on("finish",()=>{if(res.statusCode<400)invalidate.departments();});next();});
const clean = (body, actor) => ({ name: body.name?.trim(), code: body.code?.trim().toUpperCase(), type: body.type?.trim() || undefined, campus: body.campus?.trim() || undefined, status: body.status || "ACTIVE", sortOrder: Number(body.sortOrder) || 0, updatedBy: actor });
router.get("/lookup", authenticateSession, async (req, res) => ok(res, { items: await cache.getOrLoad(keys.departmentsActive,ttl.departments,()=>Department.find({ status: "ACTIVE" }).select("name code type campus").sort({ sortOrder: 1, name: 1 }).lean()) }));
router.get("/import/template", authenticateSession, requirePermission("department.import"), async (req, res) => { const buffer = await imports.makeTemplate("DEPARTMENT"); res.set({ "Content-Type": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "Content-Disposition": 'attachment; filename="Department-Import-Template.xlsx"' }); res.send(buffer); });
router.post("/import/preview", authenticateSession, requirePermission("department.import"), importValidation.uploadExcel, async (req, res) => ok(res, await imports.preview("DEPARTMENT", req.file, req.auth.userId)));
router.post("/import/:id/confirm", authenticateSession, requirePermission("department.import"), async (req, res) => ok(res, await imports.confirm(req.params.id, req.auth.userId)));
router.get("/", authenticateSession, requirePermission("department.view"), async (req, res) => { const q = req.query.search ? { $or: ["name", "code", "campus"].map((key) => ({ [key]: new RegExp(String(req.query.search).replace(/[.*+?^${}()|[\]\\]/g, "\\$&"), "i") })) } : {}; ok(res, { items: await Department.find(q).sort({ sortOrder: 1, name: 1 }).lean() }); });
router.post("/", authenticateSession, requirePermission("department.manage"), async (req, res) => { try { ok(res, { department: await Department.create({ ...clean(req.body, req.auth.userId), createdBy: req.auth.userId }) }, 201); } catch (e) { if (e.code === 11000) throw new AppError("Department code already exists", 409, "DEPARTMENT_EXISTS"); throw e; } });
router.patch("/:id", authenticateSession, requirePermission("department.manage"), async (req, res) => { if (!mongoose.Types.ObjectId.isValid(req.params.id)) throw new AppError("Department not found", 404, "DEPARTMENT_NOT_FOUND"); const item = await Department.findByIdAndUpdate(req.params.id, { $set: clean(req.body, req.auth.userId) }, { returnDocument: "after", runValidators: true }); if (!item) throw new AppError("Department not found", 404, "DEPARTMENT_NOT_FOUND"); ok(res, { department: item }); });
module.exports = router;
